### ISSUE TITLE
Modal de upload de arquivos

### ISSUE THREAD

**Issue by erikprogramador** [vedcasts/series-casos-reais#1]
Ola Vedovelli.

A ideia deste componente seria um modal, que seria aberto ao click de um botão e neste modal seria possível o upload de um arquivo que seria processado em um back-end.

Um exemplo seria o modal que é aberto quando queremos inserir uma imagem nas apresentações do Google docs.

![modal-google-drive](https://cloud.githubusercontent.com/assets/6305630/13623254/f90721a6-e583-11e5-926a-b43b1b0e9a03.png)

**Comment by vedovelli** [comment]
Sua idéia é muito boa. Já aceitei. Obrigado!

**Comment by gerardo-junior** [comment]
+1 :+1:

**Comment by gerardo-junior** [comment]
e q tal ter um crop tbm? http://pespantelis.github.io/vue-crop/

**Comment by vedovelli** [comment]
@erikprogramador Solicitação atendida! http://www.vedcasts.com.br/series/casos-reais?s=file-upload

Obrigado!
