### ISSUE TITLE
Formulários mestre/detalhe usando laravel

### ISSUE THREAD

**Issue by carloscarucce** [vedcasts/series-casos-reais#2]
Mostrar o funcionamento de forms que representam registros com relação 1 para N no Laravel.
Exemplos:
- Cadastrar um pedido e associar produtos previamente cadastrados
- Locação de filmes para um cliente em uma locadora.

A idéia é que o usuario cadastre o registro principal e seja possivel associar os registros da tabela secundária sem trocar de pagina.

**Comment by vedovelli** [comment]
+1

**Comment by mprandot** [comment]
@vedovelli  seria interessante também nesse caso, mostrar se tem como integrar  o `illuminate/html` (para abrir os forms) e o VueJs para criar os inputs e controlar as ações dentro dos forms (ex: campos obrigatórios).
