### ISSUE TITLE
Componente busca e seleção

### ISSUE THREAD

**Issue by JeanCarlos80s** [vedcasts/series-casos-reais#3]
Um input do tipo text com um botão que abre um modal, este modal teria um campo de busca e uma tabela para exibir os dados, de forma a poder selecionar uma determinada linha da coluna e retornar o valor para o input.

**Comment by vedovelli** [comment]
+1

**Comment by plcosta** [comment]
+1

**Comment by DaniloTurini** [comment]
+1

**Comment by vedovelli** [comment]
@JeanCarlos80s Finalmente!!!

http://www.vedcasts.com.br/series/casos-reais?s=busca-selecao

Obrigado por sua sugestão! Espero ter atendido o pedido integralmente!

Caso ainda não conheça, convido a conhecer www.vuejs-brasil.com.br

Também @DaniloTurini
